### ISSUE TITLE
Update docs to show support for Laravel redirects in Components

### ISSUE THREAD

**Issue by 2kodes** [calebporzio/livewire-docs#22]
Didnt know whether to make it a pull request or an issue so here goes

Currently due to [this PR](https://github.com/calebporzio/livewire/pull/93#issue-303014589)
 `return redirect()->to('/endpoint');`  works in a component 

The below dont work though
 return back();
    // Or
 return ['some' => 'data'];

**Comment by calebporzio** [comment]
Would love a PR for this!
